# Site wide configuration

title: Adil Ansari
locale: en_US
description: My blackbook
logo: site-logo.png
search: true
url: http://ansari.io

# Comments
comments: true
share: true
related: true

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
related_posts: true
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems: ["jekyll-sitemap", "jemoji"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Adil Ansari
  avatar: bio-photo.jpg
  email: me@adilansari.com
  disqus-shortname: ansari-io
  twitter: adilansari
  facebook: #username
  github: adilansari
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: adilansari
  instagram: 6xty2
  flickr: adilansari
  tumblr: #username
  pinterest: adilansari
  weibo: #userid
  google:
    plus: #username
    analytics: UA-65626670-1
    verify:
    ad-client:
    ad-slot:
  bing-verify: # verify
  google-maps: AIzaSyBsp9oYHe38DmRbGTPlYut6eGTb7S51p1I
